#include "task_lcd.h"
#include "task_key.h"
#include "hal_usart.h"
#include "pic.h"

static void lcd_data_init(void);

void task_lcd_init(void)
{
	hal_lcd_init();
	hal_key_init();
	lcd_data_init();
	hal_lcd_fill(LCD_X1,LCD_X1,LCD_X2,LCD_Y2,BLACK);
}

static void lcd_data_init(void)
{

}
void task_lcd_display(void)
{
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_0); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_1);
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_2);
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_3); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_4); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_5); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_6); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_7); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_8); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_9); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_10); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_11); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_12); 
		hal_lcd_show_picture(ASTRONAUT_IMAGE_X1,ASTRONAUT_IMAGE_Y1,ASTRONAUT_IMAGE_X_SIZE,ASTRONAUT_IMAGE_Y_SIZE,gImage_13); 
}
